"""add events table

Revision ID: 96c76b819f57
Revises: c533c9f55a0d
Create Date: 2026-06-19 15:09:37.268099

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "96c76b819f57"
down_revision = "c533c9f55a0d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("sqs_message_id", sa.String(length=256), nullable=False),
        sa.Column("type", sa.String(length=100), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_events_sqs_message_id"), ["sqs_message_id"], unique=True
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_events_sqs_message_id"))

    op.drop_table("events")
    # ### end Alembic commands ###
